"""Core business logic module for LLM-trader."""
from core.state import (
    # Global state
    balance,
    positions,
    trade_history,
    invocation_count,
    iteration_counter,
    equity_history,
    current_iteration_messages,
    last_btc_price,
    # Time provider
    get_current_time,
    set_time_provider,
    BOT_START_TIME,
    # State management
    load_state,
    save_state,
    reset_state,
    load_equity_history,
    register_equity_snapshot,
    update_balance,
    set_balance,
    get_balance,
    get_positions,
    set_position,
    remove_position,
    increment_invocation_count,
    get_invocation_count,
    increment_iteration_counter,
    get_iteration_counter,
    clear_iteration_messages,
    get_iteration_messages,
    get_equity_history,
    get_bot_start_time,
    set_last_btc_price,
    get_last_btc_price,
    # Utility functions
    strip_ansi_codes,
    escape_markdown,
)
from core.persistence import (
    load_equity_history_from_csv,
    init_csv_files_for_paths,
    save_state_to_json,
    load_state_from_json,
    append_portfolio_state_row,
    append_trade_row,
)
from core.metrics import (
    DEFAULT_RISK_FREE_RATE,
    calculate_sortino_ratio,
    calculate_pnl_for_price,
    calculate_unrealized_pnl_for_position,
    calculate_net_unrealized_pnl_for_position,
    estimate_exit_fee_for_position,
    calculate_total_margin_for_positions,
    format_leverage_display,
)

__all__ = [
    # State
    "balance",
    "positions",
    "trade_history",
    "invocation_count",
    "iteration_counter",
    "equity_history",
    "current_iteration_messages",
    "last_btc_price",
    "get_current_time",
    "set_time_provider",
    "BOT_START_TIME",
    "load_state",
    "save_state",
    "reset_state",
    "load_equity_history",
    "register_equity_snapshot",
    "update_balance",
    "set_balance",
    "get_balance",
    "get_positions",
    "set_position",
    "remove_position",
    "increment_invocation_count",
    "get_invocation_count",
    "increment_iteration_counter",
    "get_iteration_counter",
    "clear_iteration_messages",
    "get_iteration_messages",
    "get_equity_history",
    "get_bot_start_time",
    "set_last_btc_price",
    "get_last_btc_price",
    "strip_ansi_codes",
    "escape_markdown",
    # Persistence
    "load_equity_history_from_csv",
    "init_csv_files_for_paths",
    "save_state_to_json",
    "load_state_from_json",
    "append_portfolio_state_row",
    "append_trade_row",
    # Metrics
    "DEFAULT_RISK_FREE_RATE",
    "calculate_sortino_ratio",
    "calculate_pnl_for_price",
    "calculate_unrealized_pnl_for_position",
    "calculate_net_unrealized_pnl_for_position",
    "estimate_exit_fee_for_position",
    "calculate_total_margin_for_positions",
    "format_leverage_display",
]
