"""Configuration module for LLM-trader."""
from config.runtime_overrides import (
    # Runtime overrides API
    get_runtime_overrides,
    reset_runtime_overrides,
    set_runtime_override,
    get_runtime_override,
    clear_runtime_override,
    get_all_runtime_overrides,
    get_override_whitelist,
    validate_override_value,
    OVERRIDE_WHITELIST,
    VALID_TRADING_BACKENDS,
    VALID_MARKET_DATA_BACKENDS,
    VALID_INTERVALS,
    LLM_TEMPERATURE_MIN,
    LLM_TEMPERATURE_MAX,
)
from config.settings import (
    # Path setup
    BASE_DIR,
    DOTENV_PATH,
    DATA_DIR,
    # Effective config getters (override > env > default)
    get_effective_trading_backend,
    get_effective_market_data_backend,
    get_effective_interval,
    get_effective_check_interval,
    get_effective_llm_temperature,
    # API Keys
    API_KEY,
    API_SECRET,
    OPENROUTER_API_KEY,
    TELEGRAM_BOT_TOKEN,
    TELEGRAM_CHAT_ID,
    TELEGRAM_SIGNALS_CHAT_ID,
    HYPERLIQUID_WALLET_ADDRESS,
    HYPERLIQUID_PRIVATE_KEY,
    BACKPACK_API_PUBLIC_KEY,
    BACKPACK_API_SECRET_SEED,
    BACKPACK_API_BASE_URL,
    BACKPACK_API_WINDOW_MS,
    # Trading config
    PAPER_START_CAPITAL,
    HYPERLIQUID_CAPITAL,
    TRADING_BACKEND,
    MARKET_DATA_BACKEND,
    LIVE_TRADING_ENABLED,
    HYPERLIQUID_LIVE_TRADING,
    BINANCE_FUTURES_LIVE,
    BACKPACK_FUTURES_LIVE,
    BINANCE_FUTURES_MAX_RISK_USD,
    BINANCE_FUTURES_MAX_LEVERAGE,
    BINANCE_FUTURES_MAX_MARGIN_USD,
    LIVE_START_CAPITAL,
    LIVE_MAX_RISK_USD,
    LIVE_MAX_LEVERAGE,
    LIVE_MAX_MARGIN_USD,
    IS_LIVE_BACKEND,
    START_CAPITAL,
    # Symbols
    SYMBOLS,
    SYMBOL_TO_COIN,
    COIN_TO_SYMBOL,
    # System prompt
    TRADING_RULES_PROMPT,
    SYSTEM_PROMPT_SOURCE,
    describe_system_prompt_source,
    log_system_prompt_info,
    # Interval config
    DEFAULT_INTERVAL,
    INTERVAL,
    CHECK_INTERVAL,
    DEFAULT_RISK_FREE_RATE,
    # LLM config
    LLM_MODEL_NAME,
    LLM_TEMPERATURE,
    LLM_MAX_TOKENS,
    LLM_THINKING_PARAM,
    LLM_API_BASE_URL,
    LLM_API_KEY,
    LLM_API_TYPE,
    refresh_llm_configuration_from_env,
    # Indicator settings
    EMA_LEN,
    RSI_LEN,
    MACD_FAST,
    MACD_SLOW,
    MACD_SIGNAL,
    # Fee structure
    MAKER_FEE_RATE,
    TAKER_FEE_RATE,
    # Risk free rate
    RISK_FREE_RATE,
    # CSV files
    STATE_CSV,
    STATE_JSON,
    TRADES_CSV,
    DECISIONS_CSV,
    MESSAGES_CSV,
    MESSAGES_RECENT_CSV,
    MAX_RECENT_MESSAGES,
    STATE_COLUMNS,
)
from config.universe import (
    get_effective_symbol_universe,
    get_effective_coin_universe,
    set_symbol_universe,
    clear_symbol_universe_override,
    resolve_coin_for_symbol,
    resolve_symbol_for_coin,
)

__all__ = [
    "BASE_DIR",
    "DOTENV_PATH",
    "DATA_DIR",
    "API_KEY",
    "API_SECRET",
    "OPENROUTER_API_KEY",
    "TELEGRAM_BOT_TOKEN",
    "TELEGRAM_CHAT_ID",
    "TELEGRAM_SIGNALS_CHAT_ID",
    "HYPERLIQUID_WALLET_ADDRESS",
    "HYPERLIQUID_PRIVATE_KEY",
    "BACKPACK_API_PUBLIC_KEY",
    "BACKPACK_API_SECRET_SEED",
    "BACKPACK_API_BASE_URL",
    "BACKPACK_API_WINDOW_MS",
    "PAPER_START_CAPITAL",
    "HYPERLIQUID_CAPITAL",
    "TRADING_BACKEND",
    "MARKET_DATA_BACKEND",
    "LIVE_TRADING_ENABLED",
    "HYPERLIQUID_LIVE_TRADING",
    "BINANCE_FUTURES_LIVE",
    "BACKPACK_FUTURES_LIVE",
    "BINANCE_FUTURES_MAX_RISK_USD",
    "BINANCE_FUTURES_MAX_LEVERAGE",
    "BINANCE_FUTURES_MAX_MARGIN_USD",
    "LIVE_START_CAPITAL",
    "LIVE_MAX_RISK_USD",
    "LIVE_MAX_LEVERAGE",
    "LIVE_MAX_MARGIN_USD",
    "IS_LIVE_BACKEND",
    "START_CAPITAL",
    "SYMBOLS",
    "SYMBOL_TO_COIN",
    "COIN_TO_SYMBOL",
    "TRADING_RULES_PROMPT",
    "SYSTEM_PROMPT_SOURCE",
    "describe_system_prompt_source",
    "log_system_prompt_info",
    "DEFAULT_INTERVAL",
    "INTERVAL",
    "CHECK_INTERVAL",
    "DEFAULT_RISK_FREE_RATE",
    "LLM_MODEL_NAME",
    "LLM_TEMPERATURE",
    "LLM_MAX_TOKENS",
    "LLM_THINKING_PARAM",
    "LLM_API_BASE_URL",
    "LLM_API_KEY",
    "LLM_API_TYPE",
    "refresh_llm_configuration_from_env",
    "EMA_LEN",
    "RSI_LEN",
    "MACD_FAST",
    "MACD_SLOW",
    "MACD_SIGNAL",
    "MAKER_FEE_RATE",
    "TAKER_FEE_RATE",
    "RISK_FREE_RATE",
    "STATE_CSV",
    "STATE_JSON",
    "TRADES_CSV",
    "DECISIONS_CSV",
    "MESSAGES_CSV",
    "MESSAGES_RECENT_CSV",
    "MAX_RECENT_MESSAGES",
    "STATE_COLUMNS",
    # Runtime overrides
    "get_runtime_overrides",
    "reset_runtime_overrides",
    "set_runtime_override",
    "get_runtime_override",
    "clear_runtime_override",
    "get_all_runtime_overrides",
    "get_override_whitelist",
    "validate_override_value",
    "OVERRIDE_WHITELIST",
    "VALID_TRADING_BACKENDS",
    "VALID_MARKET_DATA_BACKENDS",
    "VALID_INTERVALS",
    "LLM_TEMPERATURE_MIN",
    "LLM_TEMPERATURE_MAX",
    "get_effective_symbol_universe",
    "get_effective_coin_universe",
    "set_symbol_universe",
    "clear_symbol_universe_override",
    "resolve_coin_for_symbol",
    "resolve_symbol_for_coin",
    # Effective config getters
    "get_effective_trading_backend",
    "get_effective_market_data_backend",
    "get_effective_interval",
    "get_effective_check_interval",
    "get_effective_llm_temperature",
]
